### PR TITLE
add bass sample, instrument andd track

### PR DESCRIPTION
**Pull request by CyrilleR**
Hey hello dude!
I put a bass in your drums. It seems to run well. I have put some values for detune parameter but is it implemented yet?
There is some newline issues as always with f**** osX stuff.

Tell me what you think!

### CODE REVIEW

**Comment by CyrilleR** [comment]
no conflict? Good news :)

**Comment by glimberger** [comment]
> I have put some values for detune parameter but is it implemented yet?

Yes it is !

**Comment by glimberger** [comment]
Could you get rid of the `.idea` folder ?   
There are some untracked files inside.  I can't pull your branch while it's here.

**Comment by CyrilleR** [comment]
done!

**Comment by glimberger** [comment]
great addition ! Would you like to boost some detune values before the merge

**Comment by CyrilleR** [comment]
Here you are.
It works well IMHO.

**Pull request merged**
